source setup_database.sql
source setup_foreign_keys.sql
source setup_seed_gen_type.sql
source setup_seed_gen_title.sql
source setup_seed_gen_quantities.sql
source setup_seed_gen_steps.sql
source setup_seed_gen_foods.sql